# Generated by Django 6.1.1 on 2026-09-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
